### ISSUE TITLE
pre-tile, post-untile, etc. events and states

### ISSUE THREAD

**Issue by napcok** [leukipp/cortile#14]
This will allow users to define some custom window-manager related tweaks (for example: enable/disable focus follow mouse, change window decoration, or hide “quake terminal”)
Something like, if ~/.config/cortile/pre-tile.sh exist it will be executed and so on.

What do you think?

**Comment by leukipp** [comment]
The [latest](https://github.com/leukipp/cortile/releases/latest) version has now support for socket communication.

I didn't implement real **pre**-tile hook ups, since I would like to avoid blocking the main thread.
So the tile event will fire after it was executed, but changing window decoration or doing something similar should still work even if the tiling mode is already active.

Please have a look into the [scripts](https://github.com/leukipp/cortile/tree/main/assets/scripts) folder and try out if those examples already provide the desired functionality.

**Comment by leukipp** [comment]
I have released a major release [v2.0.0](https://github.com/leukipp/cortile/releases/tag/v2.0.0) with full multi-monitor support, which brings individual tiling states per desktop (=workspace) and screen, but breaks the structures of the old socket communication protocol. 
In addition to the new features, the current code has also been heavily refactored and comes with a series of **bug fixes for OpenBox**, which I have tested already since I'm using Mabox  ([#11](https://github.com/leukipp/cortile/issues/11#issuecomment-1555907617)) in parallel.

Sorry for the breaking changes, but please take a look at the latest [scripts](https://github.com/leukipp/cortile/tree/main/assets/scripts) folder and adjust any existing logic.
I'll close this for now, but let me know if you ran into any issues on the new version.
