### ISSUE TITLE
Restore windows position when disabling the tiling

### ISSUE THREAD

**Issue by nerdyslacker** [leukipp/cortile#16]
Hi there!
First of all I want to say thank you for this great application.
I was looking for this a long time to use it in xfce.
Would it be possible to implement the feature of restoring the position after disabling the tiling ?

P.S. I see the app has multi-screen support but when I enable the tiling it affects only one screen. Is it supposed to be like that ? And if yes will there be an option to apply the tiling for all screens at once ?

**Comment by leukipp** [comment]
> Would it be possible to implement the feature of restoring the position after disabling the tiling ?

Actually, the default behavior in cortile **v1** was that untiling restores the window positions.  

But starting with cortile **v2** I had to remove this feature, mainly because of multi monitor support. The reasons are the following scenarios:
- When two screens are connected they can be individually tiled/untiled.
- Untiling one screen would move the windows back to the "original" position, which in some cases relocates the windows to another screen where they are tiled again. 
- Same issue when moving (dragging/dropping) windows between tiled and untiled screens.

Therefore I can't proper add this feature, but when you don't care about multi monitor you can try one of the older releases.

> P.S. I see the app has multi-screen support but when I enable the tiling it affects only one screen. Is it supposed to be like that ? And if yes will there be an option to apply the tiling for all screens at once ?

When you are using the latest **v2** version (and the default config) all screens and workspaces should be tiled (individually) on startup. In general keyboard shortcuts (e.g. for tiling/untiling events) are executed on the screen where you pointer currently is located.

What you describe may be a bug. Please create a new issue with OS information's and the first few `cortile -vv` log file entries, such that I can look into it.

**Comment by nerdyslacker** [comment]
@leukipp thanks for the answer.
With default configs it worked for me (can't double check it at this moment). But I disabled it in configs and then tried enabling manually. From your answer I see that it's supposed to tile individually so it's not a bug. Although if it's possible to have an option to tile everything at once with a shortcut as well that would be great. In this case the restoring part could be readded for that option I guess.

**Comment by leukipp** [comment]
The [latest](https://github.com/leukipp/cortile/releases/latest) version now has these additional configuration values,

```toml
# Disable tiling and restore windows on the current screen.
restore = "Control-Shift-R"

# The commands above will affect all screens if this key is pressed in addition (Mod1 = Alt_L).
mod_screens = "Mod1"
```

let me know if this meets your requirements.

**Comment by nerdyslacker** [comment]
@leukipp thank you for the feature, everything works as expected.
For me using `Ctrl+Shift+T` shortcut with `Alt` key somehow conflicted with opening new terminal.
Not sure if it's possible to change it to another key. If no then I'll change the shortcut for terminal. At this moment I've changed it with `Super` key as I don't use workspaces much.
But in general this is what I wanted. Thanks again :beers:
