### ISSUE TITLE
[Feature request] Support `Super-Shift-Arrow`

### ISSUE THREAD

**Issue by KaKi87** [leukipp/cortile#19]
Hello,

When moving a window across from one monitor to another using this shortcut, the window preserves its position, instead of being repositioned relatively to existing windows, like when moving it via mouse.

It would be nice to support that use case.

Thanks

**Comment by KaKi87** [comment]
Hello,
Any news on this ?
Thanks

**Comment by leukipp** [comment]
Window movements caused by external applications (or from build-in OS functionality) are hard to be handled properly, especially across all the different distro versions. Quoting from https://github.com/leukipp/cortile/issues/31#issuecomment-1849071497:
> Since cortile sets min/max window dimension values, caches and reloads window positions, tracks mouse movements and windows across multiple screens, etc. it is not recommended to be used beside other tiling solutions at the same time.

It would be easier and more reliable to implement additional functionality (e.g. move window to top/right/monitor1/monitor2/etc...) directly into cortile, but this would be part of a bigger project. 

If you often need this functionality you can create a custom script which uses [wmctrl](https://linux.die.net/man/1/wmctrl) or [xdotool](https://github.com/jordansissel/xdotool) to trigger X events. Something like minimize (untrack window), move to another screen, maximize (track window) should trigger proper X events that cortile is aware of.
```bash
active=$(xdotool getactivewindow) && xdotool windowminimize $active && xdotool windowmove $active $(xdotool getdisplaygeometry | awk '{print $1}') 0 && xdotool windowactivate $active
```

**Comment by KaKi87** [comment]
> Window movements caused by external applications (or from build-in OS functionality) are hard to be handled properly [...] It would be easier and more reliable to implement additional functionality [...] directly into cortile

Do you mean assigning the `Super-Shift-Arrow` shortcuts to Cortile instead of the desktop environment ? I'm all for it.

**Comment by leukipp** [comment]
You can already bind keys to external commands. So `Super-Shift-Arrow` registered in `config.toml` could execute a custom command (see https://github.com/leukipp/cortile/issues/43#issuecomment-1894427082) to move the current active window via script using `xdotool`.

**Comment by KaKi87** [comment]
But what's the difference between your script and desktop environment features ?

Does your script move windows in a way that allows cortile to keep tiling while the desktop environment's window movement doesn't ?

**Comment by leukipp** [comment]
> Does your script move windows in a way that allows cortile to keep tiling while the desktop environment's window movement doesn't ?

Yes, cortile tracks mouse clicks, drag events and drop events. 
So it doesn't know what to do with suddenly `jumping` windows.

It could be caused by the application themself (like firefox, spotify are reloading the last position after been added to the window stack) or it could be caused by other external applications, or some other crazy things GNOME does (like re-rendering client side decorations).

**Comment by KaKi87** [comment]
I'm sorry I don't see how I can make `Ctrl-Shift-Left` move the active window to the previous monitor and make `Ctrl-Shift-Right` move the active window to the next monitor using the configuration file or your script :thinking:

**Comment by KaKi87** [comment]
Hello ?

**Comment by leukipp** [comment]
ATM it's not planned that cortile supports move events (e.g. between monitors) caused by some external process.

**Comment by KaKi87** [comment]
How about having Cortile itself listen to `Ctrl-Shift-Arrow` and move the windows itself ?

**Comment by leukipp** [comment]
Please review [cortile-addons](https://github.com/leukipp/cortile-addons) and #65.

**Comment by KaKi87** [comment]
How about something for end users ?
Thanks

**Comment by leukipp** [comment]
Please invest at least a little bit of time looking into the resources I provided:
https://github.com/leukipp/cortile-addons/blob/main/examples/move_app_to_screen.py

**Comment by KaKi87** [comment]
This requires installing Python's package manager and setting up the script to execute at startup.

What would at least be more user-friendly would be to automatically create the `addons` directory and having the main Cortile app itself execute everything it contains, so that all the user has to do is download the file into the specified directory.

Thanks
