### ISSUE TITLE
Gaps around GTK apps, Firefox, and other apps that have client-side decorations

### ISSUE THREAD

**Issue by puyoxyz** [leukipp/cortile#3]
There are huge gaps around anything that has client side decorations because of the shadow:

![image](https://user-images.githubusercontent.com/15311104/167337069-9eb1685b-46cb-46b8-b642-84c1a4fc3624.png)

For Firefox, you can just disable its client side decorations ("Title bar" option at the bottom of the customize screen), but what about GTK?

**Comment by leukipp** [comment]
AFAIK there is no way to obtain the margin values caused by client side decorations (using the EWMH protocol).
Therefore _cortile_ is not aware of any additional layout changes, that may lead to those gaps.

Depending on your operating system and window manager settings (theme, border, shadow, ...) you can search for 
**Disable GTK3 Client-Side Decorations**. However, this could cause minor cosmetic damage to your desired appearance of windows.

For default Xfce desktop environments create a file `/home/USER/.config/gtk-3.0/gtk.css` with the content:
```css
decoration {
    margin: 0px;
    padding: 0px;
    border: none;
    box-shadow: none;
}
```
This will disable most of the client-side decorations that might cause this problem.

Let me know if you have found a solution to your particular problem.

**Comment by leukipp** [comment]
This was solved with the suggestions from [mark-cooke](https://github.com/mark-cooke) (#5).
Please have a look at the latest [release](https://github.com/leukipp/cortile/releases) and let me know if you find any further issues.
