### ISSUE TITLE
cortile cannot work with quicktile which zentile can

### ISSUE THREAD

**Issue by vincentaxhe** [leukipp/cortile#31]
After enter my Xfce session ,if cortile didnot init， quicktile  can sucessfully tile every corner in 9x2 ways. But if cortile runs ,there are six or more places quicktile cannot tile correctly ,neither xfwm4 can. even when cortile tile disabled, quicktile cannot, only if log out session and log in again with no coritle runs,quicktile can worked properly.
zentile can work with quicktile and xfwm4 ,cortile must grasp something and unwilling to share with other window manager.
I would like to tile windows automatically and manually.

**Comment by leukipp** [comment]
Since cortile sets min/max window dimension values, caches and reloads window positions, tracks mouse movements and windows across multiple screens, etc. it is not recommended to be used beside other tiling solutions at the same time.

But stopping (exiting) cortile should definitely not hinder other applications to retake control of the windows.
Here a bug was found that was fixed in the [latest](https://github.com/leukipp/cortile/releases/latest) release.

Closing for now, feel free to reopen if you still encounter similar issues.
