### ISSUE TITLE
requested feature (switcher mode) show  tiling for all open windows

### ISSUE THREAD

**Issue by ahmeteid7** [leukipp/cortile#46]
can cortile has feature that show all open windows(active and not active) as switcher app.
i know he do tiling for the raise window, what if i want to have(tiling show) which show the minimize windows too as switcher mode like skippy-xd and xfcedashboard

**Comment by leukipp** [comment]
> can cortile has feature that show all open windows(active and not active) as switcher app.

I do not fully understand the question, most switchers can be configured to also show inactive (minimized) windows.

> ...i want to have(tiling show) which show the minimize windows too as switcher mode like skippy-xd and xfcedashboard

Does anything speak against using the build in window switcher, or do you mean in cases where no window switcher is integrated in the system?

**Comment by ahmeteid7** [comment]
there is no conflict bw cortile and the switchers apps, it's good.
i mean i want not use them during using cortile, so i disabled them when cortile running. and i want to use cortile to show all opened apps: so i used that command to show all opened windows during cortile:
`wmctrl -l | awk '{print $1}' | xargs -I {} wmctrl -ia {}`
it's good, but  i wish if there option in cortile that automatically detects the maximum slaves and masters to show all opened windows.

**Comment by leukipp** [comment]
> it's good, but cortile doesn't show all opend windows,because i think the default of it is 3 slaves and one master, so i can change that default to show all opened windows?

Since v.2.4.0 the last number of maximum windows is preserved, so you could theoretically set (e.g.),
```toml
# Maximum number of allowed master windows (0 - 5).
window_masters_max = 5

# Maximum number of allowed slave windows (1 - 5).
window_slaves_max = 5
```
then use socket communication to `increase masters/slaves` before calling `wmctrl -l | awk '{print $1}' | xargs -I {} wmctrl -ia {}`. Nevertheless, there is a limit to the number of windows displayed, and as the number get larger the arrangement will become quite lumpy.

In general, **minimized windows are not known (tracked) by cortile** at all. All other open windows are tracked, but may be invisible, because they are stacked behind other slaves. Raising them to front can be done by using:

- build in taskbars/panels that show opened windows
- build in or external window switcher applications
- cortile next/previous window shortcuts:

| Keys                                                    | Description                              |
| ------------------------------------------------------- | ---------------------------------------- |
| <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>KP_2</kbd>        | Focus next window                        |
| <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>KP_8</kbd>        | Focus previous window                    |

**Comment by ahmeteid7** [comment]
> use socket communication to `increase masters/slaves`

sorry, what is the command(script) in cortile  to do that?

**Comment by ahmeteid7** [comment]
> ```toml
> # Maximum number of allowed master windows (0 - 5).
> window_masters_max = 5
> 
> # Maximum number of allowed slave windows (1 - 5).
> window_slaves_max = 5
> ```

can set that with script?

**Comment by leukipp** [comment]
Those values are the maximum values (upper bound)

```toml
# Maximum number of allowed master windows (0 - 5).
window_masters_max = 5

# Maximum number of allowed slave windows (1 - 5).
window_slaves_max = 5
```

in case you press

| Keys                                                    | Description                              |
| ------------------------------------------------------- | ---------------------------------------- |
| <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>KP_Add</kbd>      | Increase number of master windows        |
| <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Plus</kbd>        | Increase number of maximum slave windows |

several times.  
You can set that to any value you want (in this case maximal 10 windows will be visible, no matter what). The configuration is applied on app startup and you can`t change it afterwards.

When cortile is running you can still change the current max window size using the shortcuts above. By using socket communication this would be,

```bash
echo '{"Action":"master_increase"}' | nc -U /tmp/cortile.sock.in
echo '{"Action":"slave_increase"}' | nc -U /tmp/cortile.sock.in
```

but I'm still not sure if this is what you need.

**Comment by leukipp** [comment]
The socket communication will not work any more, please review [cortile-addons](https://github.com/leukipp/cortile-addons) and #65.
