### ISSUE TITLE
Automatically open applications on specific workspaces

### ISSUE THREAD

**Issue by yougotwill** [leukipp/cortile#49]
Hi, thanks for making this I've been using cortile for about 6 months now and have been loving it!

For me the last feature for a perfect setup on linux coming from macOS would be to set applications to open on a specific workspace. I see that i3 supports this but I still want to use regular xfce with cortile.

Keep up the awesome work 💪

Reference: https://i3wm.org/docs/userguide.html#assign_workspace

**Comment by leukipp** [comment]
Cortile already remembers the last window state and screen position (see #22, #44).

> For me the last feature for a perfect setup on linux coming from macOS would be to set applications to open on a specific workspace.

It would be very easy to change the existing implementation so that it also remembers the last workspace of a window class, without having to "blow up" the existing cortile config.toml file.

However, I am not sure whether this behavior is desirable, as several identical applications (e.g. file browsers) may be intentionally opened across several workspaces.

In the future, however, there will be a possibility to use custom scripts that allow windows to be assigned to a desired workspace based on one or more predefined rules.

**Comment by leukipp** [comment]
This task should now be feasible. Please review [cortile-addons](https://github.com/leukipp/cortile-addons) and #65.
