### ISSUE TITLE
Compile time method/easier way to disable auto-updating checker

### ISSUE THREAD

**Issue by Elsie19** [leukipp/cortile#76]
Is there a way that you could move the auto-updating checker to compile time, or alternatively, make it a flag that I pass into the program itself? The current method is both confusing and poorly designed with packaging in mind. Having to put a file into the *running users* cache directory *based on the running version* in order to disable an *auto-update* checker (which I think is a bad idea in the first place as it's a security vulnerability waiting to happen) is just not designed for packagers in mind.

I was thinking primarily that you could introduce a new set of artifacts to your download page that are built without the feature enabled, as that would allow us to swap out the download URL with this disabled one and continue as normal.

Alternatively you could introduce a flag like `--disable-autocheck` which would skip that step.

---

I am asking alongside [Rhino Linux](https://rhinolinux.org), which uses your program to give tiling features to our Unicorn desktop. I have noticed that since we introduced 2.3.0 (and to the current minor version) to Rhino Linux, the download counts have been climbing from 50-100 on average up to 800+ and peaking at 2.2k. We love using Cortile and would appreciate a way to disable just this feature!

CC [@ajstrongdev]: Current packager of [cortile-bin](https://pacstall.dev/packages/cortile-bin)

**Comment by leukipp** [comment]
Thanks for your feedback.

> Having to put a file into the _running users_ cache directory _based on the running version_ in order to disable an _auto-update_ checker.

Changing the cortile behavior on a "file system base" was intentionally added, to allow users to disable/enable some features in the future via gui controls that will create/delete those files.

> Alternatively you could introduce a flag like --disable-autocheck which would skip that step.

There is already a second way to alter the runtime features of cortile via the command line. For your requirements you could run cortile as:
```bash
cortile disable-release-info
```
Those additional feature flags are intentionally not documented (in `-help` and `README`), as their primary use case is for development purposes and because they could change at any time.

As mentioned in the [Install](https://github.com/leukipp/cortile?tab=readme-ov-file#installation-) section, the official supported releases are those on this github repo, but i will consider adding build flags to disable/enable cortile features for custom package builds.

**Comment by leukipp** [comment]
> There is already a second way to alter the runtime features of cortile via the command line. For your requirements you could run cortile as:
```bash
cortile disable-release-info
```

I will make sure that this flag is permanently available in upcoming releases and I'm going to document it in the `README` section, which already includes information on other flags related to potential [security concerns](https://github.com/leukipp/cortile?tab=readme-ov-file#additional-).

**Comment by leukipp** [comment]
There is [now](https://github.com/leukipp/cortile/releases/tag/v2.5.2) a way to build custom packages with features disabled by using `-ldflags`. e.g,:
```bash
go install -ldflags="-X 'main.flags=disable-dbus-interface,disable-release-info'"
```
will disable those features permanently, without the user being able to overwrite it. However the command line arguments from above will also work in the future and are now documented in the [README](https://github.com/leukipp/cortile?tab=readme-ov-file#additional-) section.

Feel free to open a new issue if you have any other concerns.
